# drln-core configuration file

[database]
server = "localhost"
port = "3306"
user = "drlm3" 
password = "drlm3db"
database = "drlm3"

[minio]
server = "localhost"
port = "9000"
ssl = false
access_key = "drlm3minio"
secret_key = "drlm3minio"

[drlmapi]
port = "50051"
user = "drlmadmin"
password = "drlm3api"

[logging]
#############################################################################
# level = trace ("Something very low level.")                               #
#         debug ("Useful debugging information.")                           #
#         info  ("Something noteworthy happened!")                          #
#         warn  ("You should probably take a look at this.")                #
#         error ("Something failed but I'm not quitting.")                  #
#         fatal ("Bye.")             --> Calls os.Exit(1) after logging     #
#         panic ("I'm bailing.")     --> Calls panic() after logging        #
#############################################################################
level = "trace"
file = "./drlm-core.log"
